export enum TextLevel {
    INLINE = -1,
    PHARAGRAPH = 0,
    H1 = 1,
    H2 = 2,
    H3 = 4,
    H4 = 6,
    H5 = 7,
    H6 = 8,
    // Span = 'span',
    // Div = 'div',
    // Bold = 'b',
    // Italic = 'i',
    // Underline = 'u',
    // Small = 'small',
    // Strong = 'strong',
    // Emphasis = 'em',
    // Quote = 'blockquote',
    // Preformatted = 'pre',
}